export const CONDITIONS_LABEL = {
  EQUALS_TO: 'IGUAL A',
  BEGINS_WITH: 'COMIENZA CON',
  ENDS_WITH: 'TERMINA EN',
  CONTAINS: 'CONTIENE',
  LESS_THAN: 'MENOR QUE',
  GREATER_THAN: 'MAYOR QUE',
  LESS_OR_EQUALS_THAN: 'MENOR O IGUAL QUE',
  GREATER_OR_EQUALS_THAN: 'MAYOR O IGUAL QUE',
  IS: 'ES',
  IS_NOT: 'NO ES',
  IS_NOT_EQUALS_TO: 'NO ES IGUAL A',
  DOES_NOT_BEGIN_WITH: 'NO COMIENZA CON',
  DOES_NOT_END_WITH: 'NO TERMINA EN',
  DOES_NOT_CONTAIN: 'NO CONTIENE',
  IS_NOT_LESS_THAN: 'NO ES MENOR QUE',
  IS_NOT_GREATER_THAN: 'NO ES MAYOR QUE',
  IS_NOT_LESS_OR_EQUALS_THAN: 'NO ES MENOR O IGUAL QUE',
  IS_NOT_GREATER_OR_EQUALS_THAN: 'NO ES MAYOR O IGUAL QUE',
};

export const CONDITIONS = {
  EQUALS_TO: 'EQUALS_TO',
  BEGINS_WITH: 'BEGINS_WITH',
  ENDS_WITH: 'ENDS_WITH',
  CONTAINS: 'CONTAINS',
  LESS_THAN: 'LESS_THAN',
  GREATER_THAN: 'GREATER_THAN',
  LESS_OR_EQUALS_THAN: 'LESS_OR_EQUALS_THAN',
  GREATER_OR_EQUALS_THAN: 'GREATER_OR_EQUALS_THAN',
  IS: 'IS',
  IS_NOT: 'IS_NOT',
  IS_NOT_EQUALS_TO: 'IS_NOT_EQUALS_TO',
  DOES_NOT_BEGIN_WITH: 'DOES_NOT_BEGIN_WITH',
  DOES_NOT_END_WITH: 'DOES_NOT_END_WITH',
  DOES_NOT_CONTAIN: 'DOES_NOT_CONTAIN',
  IS_NOT_LESS_THAN: 'IS_NOT_LESS_THAN',
  IS_NOT_GREATER_THAN: 'IS_NOT_GREATER_THAN',
  IS_NOT_LESS_OR_EQUALS_THAN: 'IS_NOT_LESS_OR_EQUALS_THAN',
  IS_NOT_GREATER_OR_EQUALS_THAN: 'IS_NOT_GREATER_OR_EQUALS_THAN',
};

export const DEFAULT_STATE = {
  field: '',
  value: '',
  type: '',
  condition: '',
  collection: '',
};

export default {
  CONDITIONS_LABEL,
  CONDITIONS,
  DEFAULT_STATE,
};
